/**
 * TanStack DB generator.
 * Generates a `db.ts` file with a TanStack DB setup using the parsed table types.
 */

import type { ParsedDatabase } from "./parse-database-types.js";

export interface TanStackOptions {
  /** Whether Zod schemas are also being generated (used for row type imports) */
  hasZodSchemas: boolean;
}

function pascalCase(s: string): string {
  return s.split("_").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("");
}

/**
 * Generate a `db.ts` file with a TanStack DB collections and database instance.
 * Imports row types from `../types/schema` (if zod is enabled) or from `../types/database`.
 */
export function generateTanStackDb(
  parsed: ParsedDatabase,
  options: TanStackOptions,
): string {
  const allTables = parsed.schemas.flatMap((s) =>
    s.tables.map((t) => ({ name: t.name, pascal: pascalCase(t.name), firstField: t.row[0]?.name ?? "id" }))
  );

  const lines: string[] = [
    "// Generated by Supabase CLI — do not edit manually",
    "// Re-generate: supa project pull",
    "",
    'import { createClient } from "@supabase/supabase-js"',
    'import { createDatabase, createCollection } from "@tanstack/db"',
    'import type { Database } from "../types/database"',
  ];

  if (options.hasZodSchemas && allTables.length > 0) {
    const imports = allTables.map((t) => `${t.pascal}Row`).join(", ");
    lines.push(`import type { ${imports} } from "../types/schema"`);
  }

  lines.push("");

  // Supabase client
  lines.push("const supabase = createClient<Database>(");
  lines.push("  process.env.NEXT_PUBLIC_SUPABASE_URL!,");
  lines.push("  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,");
  lines.push(")");
  lines.push("");

  // Collections
  for (const table of allTables) {
    const rowType = options.hasZodSchemas
      ? `${table.pascal}Row`
      : `Database["public"]["Tables"]["${table.name}"]["Row"]`;
    lines.push(`export const ${table.name}Collection = createCollection<${rowType}>({`);
    lines.push(`  id: "${table.name}",`);
    lines.push(`  getKey: (row) => String(row.${table.firstField}),`);
    lines.push("})");
    lines.push("");
  }

  // Database instance
  if (allTables.length > 0) {
    lines.push("export const db = createDatabase({");
    lines.push("  collections: {");
    for (const table of allTables) {
      lines.push(`    ${table.name}: ${table.name}Collection,`);
    }
    lines.push("  },");
    lines.push("})");
    lines.push("");
  }

  return lines.join("\n");
}
