/**
 * Zod schema generator.
 * Transforms parsed database types into zod validation schema source code.
 */

import type { ParsedDatabase, ParsedField } from "./parse-database-types.js";

// ---------------------------------------------------------------------------
// Type mapping
// ---------------------------------------------------------------------------

const TS_TO_ZOD: Record<string, string> = {
  string: "z.string()",
  number: "z.number()",
  boolean: "z.boolean()",
  Json: "z.unknown()",
  unknown: "z.unknown()",
};

/**
 * Convert a parsed field into its Zod validator expression.
 * Handles nullable, optional, and enum references.
 */
function fieldToZod(field: ParsedField, enumNames: Set<string>): string {
  let base: string;

  // Check for Database enum reference: Database["public"]["Enums"]["status"]
  const enumRef = field.baseType.match(/Database\["[^"]+"\]\["Enums"\]\["([^"]+)"\]/);
  if (enumRef) {
    base = `${enumRef[1]}Schema`;
  } else if (enumNames.has(field.baseType)) {
    base = `${field.baseType}Schema`;
  } else {
    base = TS_TO_ZOD[field.baseType] ?? "z.unknown()";
  }

  if (field.nullable) base = `${base}.nullable()`;
  if (field.optional) base = `${base}.optional()`;

  return base;
}

function pascalCase(s: string): string {
  return s.split("_").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("");
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

/**
 * Generate a `schema.ts` file containing Zod schemas for all tables and enums
 * in the parsed database.
 */
export function generateZodSchemas(parsed: ParsedDatabase): string {
  const lines: string[] = [
    "// Generated by Supabase CLI — do not edit manually",
    "// Re-generate: supa project pull",
    "",
    'import { z } from "zod"',
    "",
  ];

  for (const schema of parsed.schemas) {
    const enumNames = new Set(schema.enums.map((e) => e.name));

    // Enums
    for (const en of schema.enums) {
      lines.push(
        `export const ${en.name}Schema = z.enum([${en.values.map((v) => `"${v}"`).join(", ")}])`,
      );
      lines.push(`export type ${pascalCase(en.name)} = z.infer<typeof ${en.name}Schema>`);
      lines.push("");
    }

    // Tables
    for (const table of schema.tables) {
      const pascal = pascalCase(table.name);

      // Row
      lines.push(`export const ${table.name}RowSchema = z.object({`);
      for (const f of table.row) {
        lines.push(`  ${f.name}: ${fieldToZod(f, enumNames)},`);
      }
      lines.push("})");
      lines.push("");

      // Insert
      lines.push(`export const ${table.name}InsertSchema = z.object({`);
      for (const f of table.insert) {
        lines.push(`  ${f.name}: ${fieldToZod(f, enumNames)},`);
      }
      lines.push("})");
      lines.push("");

      // Update
      lines.push(`export const ${table.name}UpdateSchema = z.object({`);
      for (const f of table.update) {
        lines.push(`  ${f.name}: ${fieldToZod(f, enumNames)},`);
      }
      lines.push("})");
      lines.push("");

      // Type aliases
      lines.push(`export type ${pascal}Row = z.infer<typeof ${table.name}RowSchema>`);
      lines.push(`export type ${pascal}Insert = z.infer<typeof ${table.name}InsertSchema>`);
      lines.push(`export type ${pascal}Update = z.infer<typeof ${table.name}UpdateSchema>`);
      lines.push("");
    }
  }

  return lines.join("\n");
}
