import type { OpenAPIDefinition } from "../types.js"
import { findPrimaryKeys, propAccess, sanitizeIdentifier, toCamelCase } from "../utils.js"

export function generateDbContent(
  definitions: Record<string, OpenAPIDefinition>,
  options?: { clientPath?: string; clientFunctionName?: string },
): string {
  const tableNames = Object.keys(definitions).filter((name) => !name.startsWith("_"))
  const clientPath = options?.clientPath ?? "@/lib/supabase/client"
  const clientFunctionName = options?.clientFunctionName ?? "createClient"

  const lines: string[] = [
    "// ============================================================",
    "// AUTO-GENERATED — DO NOT EDIT",
    "// This file is generated by the Supabase CLI.",
    "// Any changes will be overwritten on the next `supa project pull`.",
    "// To regenerate: supa project pull",
    "// ============================================================",
    "",
    "import { supabaseCollectionOptions } from 'supa-tdb-collection'",
    `import { ${clientFunctionName} } from '${clientPath}'`,
    "import {",
    ...tableNames.map((name) => `  ${toCamelCase(sanitizeIdentifier(name))}Schema,`),
    "} from '../types/schema'",
    "import { createCollection } from '@tanstack/db'",
    "",
    "",
  ]

  for (const [tableName, definition] of Object.entries(definitions)) {
    if (tableName.startsWith("_")) continue

    const safeTableId = sanitizeIdentifier(tableName)
    const collectionName = `${toCamelCase(safeTableId)}Collection`
    const schemaName = `${toCamelCase(safeTableId)}Schema`
    const properties = definition.properties || {}
    const primaryKeys = findPrimaryKeys(properties)

    if (primaryKeys.length === 0) {
      throw new Error(
        `Table "${tableName}" has no primary key columns. TanStack DB collections require at least one primary key.`
      )
    }

    let getKeyFn: string
    if (primaryKeys.length === 1) {
      getKeyFn = `(item) => ${propAccess("item", primaryKeys[0])}!`
    } else {
      const keyParts = primaryKeys.map((k) => `\${${propAccess("item", k)}}`).join("-")
      getKeyFn = `(item) => \`${keyParts}\``
    }

    let whereFn: string
    if (primaryKeys.length === 1) {
      whereFn = `(query, item) => query.eq(${JSON.stringify(primaryKeys[0])}, ${propAccess("item", primaryKeys[0])})`
    } else {
      const whereParts = primaryKeys
        .map((k) => `.eq(${JSON.stringify(k)}, ${propAccess("item", k)})`)
        .join("")
      whereFn = `(query, item) => query${whereParts}`
    }

    lines.push(`export const ${collectionName} = createCollection(supabaseCollectionOptions({`)
    lines.push(`  tableName: ${JSON.stringify(tableName)},`)
    lines.push(`  getKey: ${getKeyFn},`)
    lines.push(`  where: ${whereFn},`)
    lines.push(`  schema: ${schemaName},`)
    lines.push(`  realtime: true,`)
    lines.push(`  supabase: ${clientFunctionName},`)
    lines.push("}))")
    lines.push("")
  }

  return lines.join("\n")
}
