import type { ParsedDatabase, ParsedField } from "../parse-database-types.js"
import { sanitizeIdentifier, toCamelCase, toPascalCase } from "../utils.js"

const TS_TO_ZOD: Record<string, string> = {
  string: "z.string()",
  number: "z.number()",
  boolean: "z.boolean()",
  Json: "z.unknown()",
  unknown: "z.unknown()",
}

function fieldToZod(rowField: ParsedField, insertOptional: boolean): string {
  let base = TS_TO_ZOD[rowField.baseType] ?? "z.unknown()"

  if (rowField.nullable) base = `${base}.nullable()`
  if (insertOptional) base = `${base}.optional()`

  return base
}

export function generateSchemasContent(parsed: ParsedDatabase): string {
  const lines: string[] = [
    "// ============================================================",
    "// AUTO-GENERATED — DO NOT EDIT",
    "// This file is generated by the Supabase CLI.",
    "// Any changes will be overwritten on the next `supa project pull`.",
    "// To regenerate: supa project pull",
    "// ============================================================",
    "",
    "import { z } from 'zod'",
    "",
  ]

  for (const schema of parsed.schemas) {
    for (const table of schema.tables) {
      const safeTableId = sanitizeIdentifier(table.name)
      const typeName = toPascalCase(safeTableId)
      const schemaName = `${toCamelCase(safeTableId)}Schema`

      lines.push(`// ${typeName} schema`)
      lines.push(`export const ${schemaName} = z.object({`)

      for (const rowField of table.row) {
        const insertField = table.insert.find((f) => f.name === rowField.name)
        const insertOptional = insertField?.optional ?? false
        const zodType = fieldToZod(rowField, insertOptional)
        lines.push(`  ${JSON.stringify(rowField.name)}: ${zodType},`)
      }

      lines.push("})")
      lines.push("")
      lines.push(`export type ${typeName} = z.infer<typeof ${schemaName}>`)
      lines.push("")
    }
  }

  return lines.join("\n")
}
